package com.ezdml.erupt.ezdemo.researchmanagement.link_project_institutions;


/*
 * Copyright © 2022 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5/23/2022 16:32:45
 */

import xyz.erupt.annotation.*;
import xyz.erupt.annotation.sub_erupt.*;
import xyz.erupt.annotation.sub_field.*;
import xyz.erupt.annotation.sub_field.sub_edit.*;
import xyz.erupt.upms.model.base.HyperModel;
import xyz.erupt.jpa.model.BaseModel;
import java.util.*;
import java.util.Date;
import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;


import com.ezdml.erupt.ezdemo.researchmanagement.project.Project;
import com.ezdml.erupt.ezdemo.researchmanagement.thirdpartyinstitutions.ThirdPartyInstitutions;

@Erupt(
    name = "link_project_institutions",
    power = @Power(importable = true, export = true)
)
@Table(name = "link_project_institutions")   //数据库表名
@Entity
public class link_project_institutions{

    //注意：本对象没有主键不符合要求，EZDML补了一个ID主键，避免运行出错
    @Id
    @GeneratedValue(generator="generator")
    @GenericGenerator(name="generator", strategy="native")
    @EruptField()
    private Long id;

    
    // @ManyToOne
    // @EruptField(
    //     views = {
    //         @View(
    //             title = "项目id",
    //             column = "id"
    //         ),
    //         @View(
    //             title = "项目名",
    //             column = "name"
    //         )
    //     },
    //     edit = @Edit(
    //         title = "项目名",
    //         notNull = true,
    //         type = EditType.REFERENCE_TABLE,
    //         referenceTableType = @ReferenceTableType(id = "id", label = "name")
    //     )
    // )
    // private Project project_id;
    
    // @ManyToOne
    // @EruptField(
    //     views = {
    //         @View(
    //             title = "机构id",
    //             column = "id"
    //         ),
    //         @View(
    //             title = "机构名",
    //             column = "name"
    //         )
    //     },
    //     edit = @Edit(
    //         title = "机构名",
    //         notNull = true,
    //         type = EditType.REFERENCE_TABLE,
    //         referenceTableType = @ReferenceTableType(id = "id", label = "name")
    //     )
    // )
    // private ThirdPartyInstitutions institution_id;
    
    // @Column(columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP",updatable = false,nullable = false)
    @Column(columnDefinition = "Integer DEFAULT 0",updatable = false,nullable = true)
    @EruptField(
        views = @View(
            title = "角色",
            desc = "Options: 1=Client, 2=Partner, 3=Regulator",
            width = "120"
        ),
        edit = @Edit(
            title = "角色",
            desc = "Options: 1=Client, 2=Partner, 3=Regulator",
            notNull = true,
            type = EditType.CHOICE,
            choiceType = @ChoiceType(vl = {
                              @VL(value = "1", label = "Client"),
                              @VL(value = "2", label = "Partner"),
                              @VL(value = "3", label = "Regulator")
                          })
        )
    )
    private Integer role;
    

}
