package com.ezdml.erupt.ezdemo.researchmanagement.staff;


/*
 * Copyright © 2022 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5/23/2022 16:32:45
 */

import xyz.erupt.annotation.*;
import xyz.erupt.annotation.sub_erupt.*;
import xyz.erupt.annotation.sub_field.*;
import xyz.erupt.annotation.sub_field.sub_edit.*;
import xyz.erupt.upms.model.base.HyperModel;
import xyz.erupt.jpa.model.BaseModel;
import java.util.*;
import java.util.Date;
import javax.persistence.*;

import com.ezdml.erupt.ezdemo.researchmanagement.link_project_staff.link_project_staff;

import org.hibernate.annotations.GenericGenerator;

@Erupt(
    name = "Staff",
    power = @Power(importable = true, export = true),
    drills = {
        @Drill(
            code = "drill", 
            title = "数据钻取",
            link = @Link(linkErupt = link_project_staff.class,  //关联表
                            joinColumn = "staff_id")  //关联表达式
        )
    }
)
@Table(name = "staff")   //数据库表名
@Entity
public class Staff{


    @Id
    @GeneratedValue(generator="generator")
    @GenericGenerator(name="generator", strategy="native")
    @EruptField(
        views = @View(
            title = "职员id",
            width = "60"
        )
    )
    private Long id;
    
    @EruptField(
        views = @View(
            title = "部门",
            width = "120"
        ),
        edit = @Edit(
            title = "部门",
            notNull = true
        )
    )
    private String category;
    
    @EruptField(
        views = @View(
            title = "姓名",
            width = "120"
        ),
        edit = @Edit(
            title = "姓名",
            notNull = true
        )
    )
    private String name;
    
    @EruptField(
        views = @View(
            title = "性别",
            desc = "Options: 0=Male, 1=Female",
            width = "120"
        ),
        edit = @Edit(
            title = "性别",
            desc = "Options: 0=Male, 1=Female",
            notNull = true,
            type = EditType.CHOICE,
            choiceType = @ChoiceType(vl = {
                              @VL(value = "0", label = "Male"),
                              @VL(value = "1", label = "Female")
                          })
        )
    )
    private Integer sex;
    
    @EruptField(
        views = @View(
            title = "出生日期",
            width = "120"
        ),
        edit = @Edit(
            title = "出生日期",
            notNull = true,
            type = EditType.DATE,
            dateType = @DateType(type = DateType.Type.DATE)
        )
    )
    private Date birth;
    
    @EruptField(
        views = @View(
            title = "入职日期",
            width = "120"
        ),
        edit = @Edit(
            title = "入职日期",
            notNull = true,
            type = EditType.DATE,
            dateType = @DateType(type = DateType.Type.DATE)
        )
    )
    private Date hireDate;
    
    @EruptField(
        views = @View(
            title = "academicTitle",
            width = "120"
        ),
        edit = @Edit(
            title = "academicTitle"
        )
    )
    private String academicTitle;
    
    @EruptField(
        views = @View(
            title = "简介",
            width = "120"
        ),
        edit = @Edit(
            title = "简介"
        )
    )
    private String intro;
    
    /*
    @OneToMany(cascade=CascadeType.ALL)
    @JoinColumn(name = "StaffId")
    @EruptField(
        edit = @Edit(title = "ProjectStaffParticipate列表", type = EditType.TAB_TABLE_ADD)
    )
    private Set<ProjectStaffParticipate> projectStaffParticipateList;
    */
    

}
