package com.ezdml.erupt.ezdemo.researchmanagement.thirdpartystaff;


/*
 * Copyright © 2022 xxx.xx All rights reserved.
 * Author: xxx (xx@xx.com)
 * Generated by EZDML 5/23/2022 16:32:45
 */

import xyz.erupt.annotation.*;
import xyz.erupt.annotation.sub_erupt.*;
import xyz.erupt.annotation.sub_field.*;
import xyz.erupt.annotation.sub_field.sub_edit.*;
import xyz.erupt.upms.model.base.HyperModel;
import xyz.erupt.jpa.model.BaseModel;
import java.util.*;
import java.util.Date;
import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;


import com.ezdml.erupt.ezdemo.researchmanagement.thirdpartyinstitutions.ThirdPartyInstitutions;

@Erupt(
    name = "ThirdPartyStaff",
    power = @Power(importable = true, export = true)
)
@Table(name = "ThirdPartyStaff")   //数据库表名
@Entity
public class ThirdPartyStaff{


    @Id
    @GeneratedValue(generator="generator")
    @GenericGenerator(name="generator", strategy="native")
    @EruptField()
    private Long id;
    
    @EruptField(
        views = @View(
            title = "姓名",
            width = "120"
        ),
        edit = @Edit(
            title = "姓名",
            notNull = true
        )
    )
    private String name;
    
    @EruptField(
        views = @View(
            title = "移动电话",
            width = "120"
        ),
        edit = @Edit(
            title = "移动电话"
        )
    )
    private String mobilePhone;
    
    @EruptField(
        views = @View(
            title = "办公电话",
            width = "120"
        ),
        edit = @Edit(
            title = "办公电话"
        )
    )
    private String officePhone;
    
    @EruptField(
        views = @View(
            title = "Email",
            width = "120"
        ),
        edit = @Edit(
            title = "Email",
            notNull = true
        )
    )
    private String email;
    
    /*
    @OneToMany(cascade=CascadeType.ALL)
    @JoinColumn(name = "contact")
    @EruptField(
        edit = @Edit(title = "第三方机构列表", type = EditType.TAB_TABLE_ADD)
    )
    private Set<ThirdPartyInstitutions> thirdPartyInstitutionsList;
    */

}
